---
title: "Assignment05"
author: "Jasmine Liu"
date: "2024-10-07"
format:
  html: default
  pdf: default
bibliography: references.bib
---
# Research Question: Does a higher adult literacy rate or primary school enrolment rate correlate with better GDP per capita?
```{python}
#| echo: true
#| eval: true
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("/Users/jasmineliu/Downloads/QTM350/Assignment05/wdi.csv")

data.head(10)
columns = data.columns.to_list()
print(columns)
print(data["country"].nunique()) 
##we have 217 countries in our dataset
```

Since we are interested in adult literacy rate, primary school enrolment rate, GDP growth rates, and GDP per capita, let's subset the dataset into only these columns for our analysis.

```{python}
#| echo: true
#| eval: true
df = data[["country","adult_literacy_rate", "primary_school_enrolment_rate", "gdp_growth_rate", "gdp_per_capita"]]

df.head()
```

We see that there's some missing values. Before we proceed to our analysis, let's first preprocess our dataset.

```{python}
#| echo: true
#| eval: true
df.isna().sum()
cleaned_data = df.dropna(subset=['adult_literacy_rate', 'primary_school_enrolment_rate', 'gdp_growth_rate', 'gdp_per_capita'])
print(cleaned_data["country"].nunique())
```

It turns out that after dropping all the missing values, we only have 32 countries left to analyze. Considering the small scale of this assignment, let's proceed with these countries.

```{python}
#| echo: true
#| eval: true
print(cleaned_data["country"].unique())
display(cleaned_data)
```

The countries we have:     'Albania', 'Bahrain', 'Benin', 'Bhutan', 'Bosnia and Herzegovina',
    'Burkina Faso', 'Burundi', 'Cambodia', 'Chad', 'Chile',
    'Dominican Republic', 'Ecuador', 'Egypt, Arab Rep.', 'Gambia, The',
    'Georgia', 'Guatemala', 'India', 'Kenya', 'Lao PDR', 'Lesotho',
    'Madagascar', 'Malawi', 'Morocco', 'Niger', 'Oman', 'Rwanda',
    'Senegal', 'Tanzania', 'Uzbekistan', 'Viet Nam',
    'West Bank and Gaza', 'Zimbabwe'


This means that the analysis we conduct will only be applicable to these countries.


Here's descriptive analysis that provides us an idea of the features' mean values, IQR values, and min, max values!
```{python}
#| echo: true
#| eval: true
display(cleaned_data['adult_literacy_rate'].describe())
display(cleaned_data['primary_school_enrolment_rate'].describe())
display(cleaned_data['gdp_growth_rate'].describe())
display(cleaned_data['gdp_per_capita'].describe())
```


Now, let's do some analysis!
```{python, fig-scap='Correlation Matrix'. Source: The World Bank (2022)}
#| echo: true
#| eval: true
correlation_matrix = cleaned_data[['adult_literacy_rate', 'primary_school_enrolment_rate', 'gdp_growth_rate', 'gdp_per_capita']].corr()

sns.heatmap(correlation_matrix, annot=True, fmt=".2f", cmap='coolwarm', square=True, cbar_kws={"shrink": .8})
plt.title('Correlation Matrix Heatmap')
plt.show()

```

We see that the correlation between GDP per capita and adult literacy rate is 0.47, let's see what they look like in a scatterplot!


```{python, fig-scap='Figure 1: Adult Literacy Rate VS GDP per capita'. Source: The World Bank (2022)}
#| label: fig-literacy-vs-gdp
#| echo: false
#| eval: true
sns.scatterplot(x='adult_literacy_rate', y='gdp_per_capita', data=cleaned_data)
plt.title('Adult Literacy Rate vs. GDP Per Capita')  # Correct usage
plt.xlabel('Adult Literacy Rate (%)')
plt.ylabel('GDP per capita')
plt.grid()
plt.savefig('literacy_vs_gdp.png', bbox_inches='tight')
plt.show()
```


We can see a pretty clear exponential curve that as adult literacy rate increases, the GDP per capita tends to increase as the adult literacy rate reaches above 70%!

```{python, fig-scap='Firgure 2: Primary School Enrolment Rate VS GDP per Capita'. Source: The World Bank (2022)}
#| label: fig-enrolment-vs-gdp
#| echo: false
#| eval: true
sns.scatterplot(x='primary_school_enrolment_rate', y='gdp_per_capita', data=cleaned_data)
plt.title(' Primary School Enrolment Rate VS GDP per capita')  # Correct usage
plt.xlabel('Primary School Enrolment (%)')
plt.ylabel('GDP per capita')
plt.grid()
plt.savefig('enrolment_vs_gdp.png', bbox_inches='tight')
plt.show()

```

Unlike the previous figure, we can't really see a general trend between primary school enrolment rate vs gdp per capita.

Let's construct a bar graph that classify the adult literacy rate into low, medium, high, and very high VS GDP per capita!

```{python,fig-cap: "Figure 3: Bar plot comparing GDP per Capita with Adult Literacy Rate". Source: The World Bank (2022)}
#| label: fig-bar-literacy-vs-gdp
#| echo: false
#| eval: true

cleaned_data['literacy_rate_group'] = pd.cut(cleaned_data['adult_literacy_rate'], bins=4, labels=["Low", "Medium", "High", "Very High"])


plt.figure(figsize=(8, 6))

sns.barplot(x='literacy_rate_group', y='gdp_per_capita', data=cleaned_data, palette='Blues', hue ='literacy_rate_group')
plt.title("Average GDP per Capita by Adult Literacy Rate Group")
plt.xlabel("Adult Literacy Rate Group")
plt.ylabel("Average GDP per Capita")
plt.show()

```

Based on [Figure 1](#fig-literacy-vs-gdp) and [Figure 3](#fig-bar-literacy-vs-gdp), there is a noticeable correlation between adult literacy rates and GDP per capita, specifically telling us that higher literacy rate is associated with higher GDP per capita. This finding aligns with other research. According to Dr. Rahman from the University of Chittagong, "taking proper initiative to  increase literacy rate of  a country will reduce its unemployment rate and increase PGDP resulting development of the country" [@inproceedings]. Additionally,  the World Literacy Foundation highlights the importance of education in economic development as "the cost of illiteracy to the global economy is estimated at USD $1.19 trillion" in 2022 [@cree2022].

```{markdown, table-cap: "Key Statistics by Country"}
|   | country                 | adult_literacy_rate | primary_school_enrolment_rate | gdp_growth_rate | gdp_per_capita  |
|---|-------------------------|---------------------|-------------------------------|-----------------|-----------------|
| 1 | Albania                 | 98.500000           | 95.606712                      | 4.856402        | 6810.114041     |
| 2 | Bahrain                 | 97.872482           | 92.344193                      | 4.891500        | 30146.925026    |
| 3 | Benin                   | 47.099998           | 113.048912                     | 6.253245        | 1304.994797     |
| 4 | Bhutan                  | 72.099998           | 103.800003                     | 5.213868        | 3704.018395     |
| 5 | Bosnia and Herzegovina  | 98.300003           | 87.822220                      | 4.226811        | 7587.588173     |
| 6 | Burkina Faso            | 34.490002           | 82.356796                      | 1.777915        | 830.043966      |
| 7 | Burundi                 | 75.540001           | 103.901001                     | 1.848999        | 259.025031      |
| 8 | Cambodia                | 83.779999           | 109.959000                     | 5.239810        | 1759.608023     |
| 9 | Chad                    | 27.280001           | 90.364120                      | 2.804341        | 699.463254      |
|10 | Chile                   | 97.160004           | 100.192268                     | 2.058740        | 15411.173954    |
|11 | Dominican Republic      | 95.500000           | 100.492287                     | 4.858324        | 10111.245711    |
|12 | Ecuador                 | 93.948120           | 97.534103                      | 6.186139        | 6476.644575     |
|13 | Egypt, Arab Rep.        | 74.500000           | 91.590179                      | 6.587846        | 4295.407496     |
|14 | Gambia, The             | 58.669998           | 92.320000                      | 4.917821        | 803.808655      |
|15 | Georgia                 | 99.574989           | 104.548119                     | 10.958532       | 6729.846599     |
|16 | Guatemala               | 84.269997           | 103.906227                     | 4.118004        | 5473.208564     |
|17 | India                   | 76.322777           | 111.084000                     | 6.987039        | 2366.309609     |
|18 | Kenya                   | 82.879997           | 97.185997                      | 4.846635        | 2099.298568     |
|19 | Lao PDR                 | 87.519997           | 97.223000                      | 2.707427        | 2054.430781     |
|20 | Lesotho                 | 82.010002           | 88.611778                      | 1.285504        | 992.857328      |
|21 | Madagascar              | 77.480003           | 138.192001                     | 3.796199        | 516.772197      |
|22 | Malawi                  | 68.080002           | 126.438004                     | 0.923450        | 643.433196      |
|23 | Morocco                 | 77.349998           | 114.169991                     | 1.258544        | 3441.991455     |
|24 | Niger                   | 38.099998           | 68.331413                      | 11.900000       | 588.899048      |
|25 | Oman                    | 97.339058           | 90.096809                      | 4.311254        | 25056.794861    |
|26 | Rwanda                  | 78.763184           | 134.930344                     | 8.157734        | 966.571293      |
|27 | Senegal                 | 57.669998           | 83.278702                      | 3.821856        | 1594.985153     |
|28 | Tanzania                | 82.019997           | 95.504997                      | 4.566006        | 1193.359619     |
|29 | Uzbekistan              | 99.999977           | 94.194000                      | 5.668817        | 2276.161233     |
|30 | Viet Nam                | 96.133263           | 123.134003                     | 8.123514        | 4179.011790     |
|31 | West Bank and Gaza      | 97.843842           | 91.764587                      | 4.082760        | 3799.955270     |
|32 | Zimbabwe                | 89.849998           | 95.790001                      | 6.522375        | 1676.821489     |
```
